<?php

use Illuminate\Database\Seeder;

class PetitionTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = date("Y-m-d H:i:s");
        DB::table('petition_types')->insert([
            [
                'id'                    =>1,
                'title'                 =>'Título Tipo1',
                'header_address'        =>'IV',
                'header_num_process'    => 'S',
                'header_author'         =>'QC',
                'header_culprit'        =>'QC',
                'header_name_action'    =>'LB',
                'active'                =>1,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ],    
            [
                'id'                    =>2,
                'title'                 =>'Título Tipo2',
                'header_address'        =>'NV',
                'header_num_process'    =>"N",
                'header_author'         =>'JQ',
                'header_culprit'        =>'JQ',
                'header_name_action'    =>'ML',
                'active'                => 0,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ], 
            [
                'id'                    =>3,
                'title'                 =>'Título Tipo3',
                'header_address'        =>'IV',
                'header_num_process'    =>'S',
                'header_author'         =>'QC',
                'header_culprit'        =>'JQ',
                'header_name_action'    =>'ML',
                'active'                =>1,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ], 
            [
                'id'                    =>4,
                'title'                 =>'Título Tipo3',
                'header_address'        =>'NV',
                'header_num_process'    =>'N',
                'header_author'         =>'JQ',
                'header_culprit'        =>'QC',
                'header_name_action'    =>'LB',
                'active'                =>0,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ],
            [
                'id'                    =>5,
                'title'                 =>'Título Tipo1',
                'header_address'        =>'IV',
                'header_num_process'    => 'S',
                'header_author'         =>'QC',
                'header_culprit'        =>'QC',
                'header_name_action'    =>'LB',
                'active'                =>1,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ],    
            [
                'id'                    =>6,
                'title'                 =>'Título Tipo2',
                'header_address'        =>'NV',
                'header_num_process'    =>"N",
                'header_author'         =>'JQ',
                'header_culprit'        =>'JQ',
                'header_name_action'    =>'ML',
                'active'                => 0,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ], 
            [
                'id'                    =>7,
                'title'                 =>'Título Tipo3',
                'header_address'        =>'IV',
                'header_num_process'    =>'S',
                'header_author'         =>'QC',
                'header_culprit'        =>'JQ',
                'header_name_action'    =>'ML',
                'active'                =>1,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ], 
            [
                'id'                    =>8,
                'title'                 =>'Título Tipo3',
                'header_address'        =>'NV',
                'header_num_process'    =>'N',
                'header_author'         =>'JQ',
                'header_culprit'        =>'QC',
                'header_name_action'    =>'LB',
                'active'                =>0,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ], 
            [
                'id'                    =>9,
                'title'                 =>'Título Tipo1',
                'header_address'        =>'IV',
                'header_num_process'    => 'S',
                'header_author'         =>'QC',
                'header_culprit'        =>'QC',
                'header_name_action'    =>'LB',
                'active'                =>1,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ],    
            [
                'id'                    =>10,
                'title'                 =>'Título Tipo2',
                'header_address'        =>'NV',
                'header_num_process'    =>"N",
                'header_author'         =>'JQ',
                'header_culprit'        =>'JQ',
                'header_name_action'    =>'ML',
                'active'                => 0,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ], 
            [
                'id'                    =>11,
                'title'                 =>'Título Tipo3',
                'header_address'        =>'IV',
                'header_num_process'    =>'S',
                'header_author'         =>'QC',
                'header_culprit'        =>'JQ',
                'header_name_action'    =>'ML',
                'active'                =>1,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ], 
            [
                'id'                    =>12,
                'title'                 =>'Título Tipo3',
                'header_address'        =>'NV',
                'header_num_process'    =>'N',
                'header_author'         =>'JQ',
                'header_culprit'        =>'QC',
                'header_name_action'    =>'LB',
                'active'                =>0,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ],
            [
                'id'                    =>13,
                'title'                 =>'Título Tipo1',
                'header_address'        =>'IV',
                'header_num_process'    => 'S',
                'header_author'         =>'QC',
                'header_culprit'        =>'QC',
                'header_name_action'    =>'LB',
                'active'                =>1,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ],    
            [
                'id'                    =>14,
                'title'                 =>'Título Tipo2',
                'header_address'        =>'NV',
                'header_num_process'    =>"N",
                'header_author'         =>'JQ',
                'header_culprit'        =>'JQ',
                'header_name_action'    =>'ML',
                'active'                => 0,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ], 
            [
                'id'                    =>15,
                'title'                 =>'Título Tipo3',
                'header_address'        =>'IV',
                'header_num_process'    =>'S',
                'header_author'         =>'QC',
                'header_culprit'        =>'JQ',
                'header_name_action'    =>'ML',
                'active'                =>1,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ], 
            [
                'id'                    =>16,
                'title'                 =>'Título Tipo3',
                'header_address'        =>'NV',
                'header_num_process'    =>'N',
                'header_author'         =>'JQ',
                'header_culprit'        =>'QC',
                'header_name_action'    =>'LB',
                'active'                =>0,   
                'created_at'            => $now,
                'updated_at'            => $now,
            ],                
        ]);
    }
}
